### ISSUE TITLE
Can not view archived content block page when they content a banner block

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-elemental-bannerblock#21]
# Affected Version
SilverStripe 4.3-RC1

# Description
If you archived a content block page with a banner block, you'll get the following error when you try to view the archived view of the page.
```
[Emergency] Uncaught BadMethodCallException: Object->__call(): the method 'getLinkText' does not exist on 'SilverStripe\ElementalBannerBlock\Form\BlockLinkField'
```

# Steps to reproduce
* Create a content block page.
* Add a banner block and fill in the content.
* Archive the page.
* Try to access the archived page.

https://youtu.be/7mTlLhxunuw

**Comment by ScopeyNZ** [comment]
Thanks @maxime-rainville can you please provide the versions of elemental _and_ elemental-bannerblock you're using as well? It looks like you're running at least elemental 4.0.0-beta1?

**Comment by maxime-rainville** [comment]
* dnadesign/silverstripe-elemental 4.0.0-beta1
* silverstripe/elemental-bannerblock 2.0.0-beta1

**Comment by ScopeyNZ** [comment]
Just tried with the latest development versions and it seems fine. I'll try to spot what I'm doing wrong or find where it was fixed later.

**Comment by chillu** [comment]
Nope, not fixed - this is what broke it: https://github.com/silverstripe/silverstripe-elemental-bannerblock/commit/3cd243854b7b4d68e86dda8993bfdce93207abdb#diff-9febe33e35142c914c40f462aa800eb6

The readonly field still refers to those removed methods: https://github.com/silverstripe/silverstripe-elemental-bannerblock/blob/master/src/Form/BlockLinkField_Readonly.php#L40

I'm not sure how you've set up React form field readonly versions. Doesn't look like it handles it, and still relies on server-rendered readonly? I've added back some methods, and it works again: https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/24

**Comment by robbieaverill** [comment]
Fixed in https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/24
